const ALERT = "ALERT";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const NEW_MESSAGE = "NEW_MESSAGE";

export {
  ALERT,
  REFETCH_CHAT,
  NEW_ATTACHMENT,
  NEW_MESSAGE,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  START_TYPING,
  STOP_TYPING,
};
